Backend/TN.UI/Areas/Base/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TN.Domain.Model;
using TN.Infrastructure.Interfaces;
using TN.UI.Areas.Base.Controllers;
using TN.UI.Extensions;

namespace TN.UI.Areas.Setting.Controllers
{
    [Area("Base")]
    public class SettingsController : BaseController
    {
        private readonly ILogger _logger;
        private readonly IFileRepository _iFileRepository;
        private readonly IOptions<BaseSettings> _baseSettings;
        private readonly IOptions<EmailSettings> _emailSettings;
        private readonly IHostingEnvironment _iHostingEnvironment;
        private readonly IEmailSenderRepository _iEmailSenderRepository;
        public SettingsController(
            ILogger<BaseController> logger, 
            IOptions<BaseSettings> baseSettings, 
            IFileRepository iFileRepository, 
            IHostingEnvironment iHostingEnvironment, 
            IOptions<EmailSettings> emailSettings,
            IEmailSenderRepository iEmailSenderRepository
            )
        {
            controllerName = "SettingsController";
            tableName = "User";

            _logger = logger;
            _baseSettings = baseSettings;
            _iFileRepository = iFileRepository;
            _iHostingEnvironment = iHostingEnvironment;
            _emailSettings = emailSettings;
            _iEmailSenderRepository = iEmailSenderRepository;
        }
        [HttpGet]
        [AuthorizePermission("Index")]
        public IActionResult Index()
        {
            return View(_baseSettings.Value);
        }
        [AuthorizePermission("Index")]
        [HttpPost,ValidateAntiForgeryToken,ActionName("Index")]
        public async Task<ResponseModel> IndexPost(BaseSettings model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string valueBeffo = Newtonsoft.Json.JsonConvert.SerializeObject(model);
                    _iFileRepository.SettingsUpdate(_iHostingEnvironment.ContentRootPath + "/appsettings.Base.json", new { BaseSettings = model });
                    var data = _baseSettings.Value;
                    data.DocumentsMaxSize = model.DocumentsMaxSize;
                    data.ImagesType = model.ImagesType;
                    data.ImagesMaxSize = model.ImagesMaxSize;
                    data.DocumentsType = model.DocumentsType;
                    data.IsCapCha = model.IsCapCha;
                    data.CapChaDataSitekey = model.CapChaDataSitekey;
                    data.CapChaSecret = model.CapChaSecret;
                    data.GoogleMapKey = model.GoogleMapKey;
                    await AddLog(new LogModel { Action = $"Cập nhật cấu hình chung", ObjectId = 0, Type = LogType.Danger, ValueAfter = model, StrValueBefore= valueBeffo });
                    return new ResponseModel() { Output = 1, Message = "Cập nhật cấu hình thành công.", Type = ResponseTypeMessage.Success };
                }
                else
                {
                    return new ResponseModel() { Output = 2, Message = "Bạn chưa nhập đầy đủ thông tin, hoặc tên quyền này đã tồn tại.", Type = ResponseTypeMessage.Warning };
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.GENERATE_ITEMS, "#Trong-[Log]{0}", ex);
            }
            return new ResponseModel() { Output = -1, Message = "Đã xảy ra lỗi, vui lòng F5 trình duyệt và thử lại.", Type = ResponseTypeMessage.Danger, Status = false };
        }
        [HttpGet]
        [AuthorizePermission("Email")]
        public IActionResult Email()
        {
            return View(_emailSettings.Value);
        }
        [AuthorizePermission("Index")]
        [HttpPost, ValidateAntiForgeryToken, ActionName("Email")]
        public async Task<ResponseModel> EmailPost(EmailSettings model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string valueBeffo = Newtonsoft.Json.JsonConvert.SerializeObject(model);
                    _iFileRepository.SettingsUpdate(_iHostingEnvironment.ContentRootPath + "/appsettings.Email.json", new { EmailSettings = model });

                    var data = _emailSettings.Value;
                    data.Email = model.Email;
                    data.From = model.From;
                    data.Host = model.Host;
                    data.Password = model.Password;
                    data.Port = model.Port;

                    await AddLog(new LogModel { Action = $"Cập nhật cấu hình email.", ObjectId = 0, Type = LogType.Danger, ValueAfter = model, StrValueBefore = valueBeffo });
                    return new ResponseModel() { Output = 1, Message = "Cập nhật cấu hình thành công.", Type = ResponseTypeMessage.Success };
                }
                else
                {
                    return new ResponseModel() { Output = 2, Message = "Bạn chưa nhập đầy đủ thông tin, hoặc tên quyền này đã tồn tại", Type = ResponseTypeMessage.Warning };
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.GENERATE_ITEMS, "#Trong-[Log]{0}", ex);
            }
            return new ResponseModel() { Output = -1, Message = "Đã xảy ra lỗi, vui lòng F5 trình duyệt và thử lại", Type = ResponseTypeMessage.Danger, Status = false };
        }
        [AuthorizePermission("Email")]
        [HttpPost, ValidateAntiForgeryToken, ActionName("SendEmail")]
        public async Task<ResponseModel> SendEmailPost(string email)
        {
            try
            {
                var output = await _iEmailSenderRepository.SendAsync(_emailSettings.Value,email,"Email test success.", "Email test success.");
                if(output)
                {
                    return new ResponseModel() { Output = 1, Message = "Gửi email thành công.", Type = ResponseTypeMessage.Success };
                }
                else
                {
                    return new ResponseModel() { Output = 1, Message = "Gửi email thất bại.", Type = ResponseTypeMessage.Warning };
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.GENERATE_ITEMS, "#Trong-[Log]{0}", ex);
            }
            return new ResponseModel() { Output = -1, Message = "Đã xảy ra lỗi, vui lòng F5 trình duyệt và thử lại", Type = ResponseTypeMessage.Danger, Status = false };
        }
    }
}

Backend/TN.UI/Areas/User/Controllers/RoleAreaManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TN.Domain.Model;
using TN.Infrastructure.Repositories;
using TN.Infrastructure.Interfaces;
using TN.UI.Areas.Base.Controllers;
using TN.UI.Extensions;
using static TN.UI.Extensions.DataUserInfo;
namespace TN.UI.Areas.Manager.Controllers
{
    [Area("User")]
    [IsSupperAdminAuthorizePermission]
    public class RoleAreaManagerController : Controller
    {
        private readonly IHostingEnvironment _iHostingEnvironment;
        private readonly ILogger _logger;
        private readonly LogSettings _logSettings;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IOptions<BaseSettings> _baseSettings;
        private readonly ILogRepository _iLogRepository;
        private readonly IRoleAreaRepository _iRoleAreaRepository;
        private readonly IRoleControllerRepository _iRoleControllerRepository;
        public RoleAreaManagerController(
            ILogger<RoleAreaManagerController> logger,
            IHostingEnvironment hostingEnvironment,
            IOptions<BaseSettings> baseSettings,
            IHostingEnvironment iHostingEnvironment,
            ILogRepository iLogRepository,
            IOptions<LogSettings> logSettings,
            IRoleAreaRepository iRoleAreaRepository,
            IRoleControllerRepository iRoleControllerRepository
        )
        {
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;
            _baseSettings = baseSettings;
            _iHostingEnvironment = iHostingEnvironment;
            _iLogRepository = iLogRepository;
            _logSettings = logSettings.Value;
            _iRoleAreaRepository = iRoleAreaRepository;
            _iRoleControllerRepository = iRoleControllerRepository;
        }
        #region [Index]

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost, ActionName("Index")]

        public async Task<IActionResult> IndexPost(int? page, int? limit, string key, string ordertype, string orderby)
        {
            page = page < 0 ? 1 : page;
            limit = (limit > 100 || limit < 10) ? 10 : limit;
            var data = await _iRoleAreaRepository.SearchPagedList(
            page ?? 1,
            limit ?? 10,
            m => (m.Name.Contains(key) || key == null || m.Id.Contains(key)),
            OrderByExtention(ordertype, orderby));
            data.ReturnUrl = Url.Action("Index", new { page, limit, key, ordertype, orderby });
            return View("IndexAjax", data);
        }
        private Func<IQueryable<RoleArea>, IOrderedQueryable<RoleArea>> OrderByExtention(string ordertype, string orderby)
        {
            Func<IQueryable<RoleArea>, IOrderedQueryable<RoleArea>> functionOrder = null;
            switch (orderby)
            {
                case "name":
                    functionOrder = ordertype == "asc" ? EntityExtention<RoleArea>.OrderBy(m => m.OrderBy(x => x.Name)) : EntityExtention<RoleArea>.OrderBy(m => m.OrderByDescending(x => x.Name));
                    break;
                default:
                    functionOrder = ordertype == "asc" ? EntityExtention<RoleArea>.OrderBy(m => m.OrderBy(x => x.Order)) : EntityExtention<RoleArea>.OrderBy(m => m.OrderByDescending(x => x.Order));
                    break;
            }
            return functionOrder;
        }
        #endregion
        #region [Create]
        [HttpGet]

        public IActionResult Create()
        {
            var dl = new RoleAreaModel();
            return View(dl);
        }
        [HttpPost, ActionName("Create")]

        public async Task<ResponseModel> CreatePost(RoleAreaModel use, string returnurl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var ktId = await _iRoleAreaRepository.AnyAsync(m => m.Id == use.Id);
                    if (ktId)
                    {
                        return new ResponseModel() { Output = 1, Message = "Mã quyền area đã tồn tại", Type = ResponseTypeMessage.Warning, IsClosePopup = false };
                    }
                    var data = new RoleArea
                    {
                        Id = use.Id,
                        Status = use.Status,
                        Name = use.Name,
                        Order = use.Order
                    };
                    await _iRoleAreaRepository.AddAsync(data);
                    await _iRoleAreaRepository.Commit();
                    return new ResponseModel() { Output = 1, Message = "Thêm mới dữ liệu thành công ", Type = ResponseTypeMessage.Success, IsClosePopup = true };
                }
                return new ResponseModel() { Output = 0, Message = "Bạn chưa nhập đầy đủ thông tin", Type = ResponseTypeMessage.Warning };
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.GENERATE_ITEMS, "#Trong-[Log]{0}", ex);
            }
            return new ResponseModel() { Output = -1, Message = "Đã xảy ra lỗi, vui lòng F5 trình duyệt và thử lại", Type = ResponseTypeMessage.Danger, Status = false };
        }

        #endregion
        #region [Edit]
        [HttpGet]

        public async Task<IActionResult> Edit(string id)
        {
            var dl = await _iRoleAreaRepository.SearchOneAsync(m => m.Id == id);
            if (dl == null)
            {
                return View("404");
            }
            var model = MapModel<RoleAreaModel>.Go(dl);
            return View(model);
        }
        [HttpPost, ActionName("Edit")]

        public async Task<ResponseModel> EditPost(RoleAreaModel use, string id, string returnurl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var dl = await _iRoleAreaRepository.SearchOneAsync(m => m.Id == id);
                    if (dl == null)
                    {
                        return new ResponseModel() { Output = 0, Message = "Dữ liệu không tồn tại, vui lòng thử lại.", Type = ResponseTypeMessage.Warning };
                    }

                    dl.Status = use.Status;
                    dl.Name = use.Name;
                    dl.Order = use.Order;
                    _iRoleAreaRepository.Update(dl);
                    await _iRoleAreaRepository.Commit();
                    return new ResponseModel() { Output = 1, Message = "Cập nhật dữ liệu thành công.", Type = ResponseTypeMessage.Success, IsClosePopup = true };
                }
                return new ResponseModel() { Output = -2, Message = "Bạn chưa nhập đầy đủ thông tin.", Type = ResponseTypeMessage.Warning };
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.GENERATE_ITEMS, "#Trong-[Log]{0}", ex);
            }
            return new ResponseModel() { Output = -1, Message = "Đã xảy ra lỗi, vui lòng F5 trình duyệt và thử lại.", Type = ResponseTypeMessage.Danger, Status = false };
        }
        #endregion
        #region [Delete]
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]

        public async Task<ResponseModel> DeletePost(string id)
        {
            try
            {
                // Kiểm tra dữ liệu đang sử dụng ở controller
                var ktC = await _iRoleControllerRepository.AnyAsync(x => x.AreaId == id);
                if (ktC)
                {
                    return new ResponseModel() { Output = 9, IsUse = true, Message = "Dữ liệu này đang được sử dụng ở quản lý quyền controller, vui lòng bỏ chọn dữ liệu này rồi thực hiện lại.", Type = ResponseTypeMessage.Warning };
                }

                var kt = await _iRoleAreaRepository.SearchOneAsync(m => m.Id == id);
                if (kt == null)
                {
                    return new ResponseModel() { Output = 0, Message = "Dữ liệu không tồn tại, vui lòng thử lại.", Type = ResponseTypeMessage.Warning };
                }
                _iRoleAreaRepository.Delete(kt);
                await _iRoleAreaRepository.Commit();

                return new ResponseModel() { Output = 1, Message = "Xóa dữ liệu thành công.", Type = ResponseTypeMessage.Success,IsClosePopup=true };
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.GENERATE_ITEMS, "#Trong-[Log]{0}", ex);
            }
            return new ResponseModel() { Output = -1, Message = "Đã xảy ra lỗi, vui lòng F5 trình duyệt và thử lại.", Type = ResponseTypeMessage.Danger, Status = false };
        }
        #endregion
    }
}

Backend/TN.UI/Views/Shared/404.cshtml
@{
    Layout = null;
}
<div class="five-zero-zero">
    <button title="Đóng cửa sổ" type="button" class="close btnclose-t" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="five-zero-zero-container">
        <div class="error-code">404</div>
        <div class="error-message">Dữ liệu này không tồn tại, có thể bị xóa hoặc bị vô hiệu hóa!</div>
    </div>
    <!-- Jquery Core Js -->
    <script src="/Content/Admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="/Content/Admin/plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="/Content/Admin/plugins/node-waves/waves.js"></script>
</div>

Backend/TN.UI/Views/Shared/_Login.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>ĐĂNG NHẬP | QUẢN TRỊ WEBSITE</title>
    <!-- Favicon-->
    <link rel="icon" href="/Content/Admin/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <link asp-append-version="true" href="~/Content/Admin/site.min.css" rel="stylesheet" />
</head>
<body class="login-page">
    @RenderBody()
</body>
</html>

<script src="~/Content/Admin/js/jquery.min.js"></script>
<script asp-append-version="true" src="~/Content/Admin/site.min.js"></script>
<script src="~/Content/Admin/js/script.js"></script>
@RenderSection("Scripts", required: false)
<script>
    @Html.Raw(ViewData["msg"])
</script>

Backend/TN.UI/Views/Shared/_MenuAdmin.cshtml
<div class="menu">
    <ul class="list" id="menuleftadmin">
        <li class="header">ĐIỀU KHIỂN</li>
        <li data-checked data-role-10 class="cap1 isDasb">
            <a href="/Admin">
                <i class="material-icons">home</i>
                <span>Trang điều khiển</span>
            </a>
        </li>
        <li data-checked data-role-120 data-role-130 data-role-140 data-role-150 class="cap1">
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">local_convenience_store</i>
                <span>Quản lý đơn vị vận tải</span>
            </a>
            <ul class="ml-menu">
                <li data-checked data-role-120 class="cap2">
                    <a asp-action="Index" asp-area="Company" asp-controller="TransportCompanyManager">Đơn vị vận tải</a>
                </li>
                <li data-checked data-role-130 class="cap2">
                    <a asp-action="Index" asp-area="Company" asp-controller="VehicleManager">Phương tiện</a>
                </li>
                <li data-checked data-role-150 class="cap2">
                    <a asp-action="Index" asp-area="Company" asp-controller="TransportCompanyEmployeeManager">Lái xe, tiếp viên</a>
                </li>
                <li data-checked data-role-140 class="cap2">
                    <a asp-action="Index" asp-area="Company" asp-controller="TransportCompanyMistakeManager">Danh mục vi phạm</a>
                </li>
            </ul>
        </li>
        <li data-checked data-role-100 data-role-110 class="cap1">
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">business</i>
                <span>Quản lý trường, học sinh</span>
            </a>
            <ul class="ml-menu">
                <li data-checked data-role-100 class="cap2">
                    <a asp-action="Index" asp-area="School" asp-controller="SchoolManager">Quản lý trường, lớp</a>
                </li>
                <li data-checked data-role-110 class="cap2">
                    <a asp-action="Index" asp-area="School" asp-controller="StudentManager">Quản lý học sinh</a>
                </li>
            </ul>
        </li>
        <li data-checked data-role-155 data-role-151 data-role-159 data-role-167 class="cap1">
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">directions_car</i>
                <span>Quản lý CTDD học sinh</span>
            </a>
            <ul class="ml-menu">
                <li data-checked data-role-155 class="cap2">
                    <a asp-action="Index" asp-area="Route" asp-controller="StationManager">Quản lý danh mục trạm</a>
                </li>
                <li data-checked data-role-151 class="cap2">
                    <a asp-action="Index" asp-area="Route" asp-controller="StudentGroupManager">Lên danh sách học sinh đi xe</a>
                </li>
                <li data-checked data-role-159 class="cap2">
                    <a asp-action="Index" asp-area="Route" asp-controller="RouteManager">Lên lộ trình tuyền</a>
                </li>
            </ul>
        </li>
        <li class="cap2" data-checked data-role-167>
            <a asp-action="Index" asp-area="Route" asp-controller="ConfirmationTripsManager">
                <i class="material-icons">check</i>
                <span>Xác nhận chuyến đi</span>
            </a>
        </li>
        <li class="cap2" data-checked data-role-185>
            <a asp-action="Index" asp-area="Report" asp-controller="TripsReport">
                <i class="material-icons">content_paste</i>
                <span>Báo cáo thống kê</span>
            </a>
        </li>
        <li class="header" data-checked data-role-5 data-role-1 data-role-181>HỆ THỐNG</li>
        <li class="cap2" data-checked data-role-181>
            <a asp-action="Index" asp-controller="DeviceManager" asp-area="Manager">
                <i class="material-icons">nfc</i>
                <span>Quản lý thiết bị vân tay</span>
            </a>
        </li>
        <li class="cap1" data-checked data-role-5 data-role-1>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">person_outline</i>
                <span>Quản trị tài khoản</span>
            </a>
            <ul class="ml-menu">
                <li class="cap2" data-checked data-role-5>
                    <a asp-action="Index" asp-controller="UserManager" asp-area="User">Quản lý tài khoản</a>
                </li>
                <li class="cap2" data-checked data-role-1>
                    <a asp-action="Index" asp-controller="RoleManager" asp-area="User">Quyền tài khoản</a>
                </li>
            </ul>
        </li>
        <li data-checked data-role-27 class="cap2">
            <a asp-action="Index" asp-controller="LogManager" asp-area="Log">
                <i class="material-icons">update</i>
                <span>Log người dùng</span>
            </a>
        </li>
        <li class="cap2">
            <a asp-action="Index" asp-controller="Settings" asp-area="Base">
                <i class="material-icons">settings</i>
                <span>Cấu hình hệ thống</span>
            </a>
        </li>
        <li isSupperadmin class="cap1">
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">brightness_low</i>
                <span>Cấu hình quyền</span>
            </a>
            <ul class="ml-menu">
                <li class="cap2">
                    <a asp-action="Index" asp-controller="RoleGroupManager" asp-area="User">Quản lý nhóm</a>
                </li>
                <li class="cap2">
                    <a asp-action="Index" asp-controller="RoleAreaManager" asp-area="User">Quản lý Area</a>
                </li>
                <li class="cap2">
                    <a asp-action="Index" asp-controller="RoleControllerManager" asp-area="User">Quản lý controller</a>
                </li>
                <li class="cap2">
                    <a asp-action="Index" asp-controller="RoleActionManager" asp-area="User">Quản lý Action</a>
                </li>
            </ul>
        </li>
    </ul>
</div>